kind: Deployment
apiVersion: apps/v1
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: {{ .Values.kustomize.namePrefix }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.kustomize.namePrefix }}-app
    spec:
      volumes:
        - name: {{ .Values.volumes.name }}
          configMap:
            name: configmap
      containers:
        - name: app
          resources:
            requests:
              cpu: {{ .Values.kustomize.resources.requests.cpu }}
              memory: {{ .Values.kustomize.resources.requests.memory }}
            limits:
              cpu: {{ .Values.kustomize.resources.limits.cpu }}
              memory: {{ .Values.kustomize.resources.limits.memory }}
          volumeMounts:
            - name: {{ .Values.volumes.name }}
              mountPath: {{ .Values.volumes.mountPath }}
          envFrom:
            - configMapRef:
                name: {{ .Values.kustomize.configmapName }}


