{{- if eq .Values.route.type "route" }}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.route.name }} 
  annotations:
    cert-utils-operator.redhat-cop.io/certs-from-secret: {{ .Values.kustomize.namePrefix }}-secret-ca-cert
spec:
  {{- if eq .Values.host.type "custom" }}
  host: '{{ .Values.host.name }}'
  {{- else}}
  host: '{{ .Values.kustomize.namePrefix }}-{{ .Values.kustomize.namespace }}.{{ .Values.route.domain }}'
  {{- end }}
  to:
    kind: Service
    name: {{ .Values.kustomize.namePrefix }}-service
    weight: 100
  port:
    targetPort: {{ .Values.applicationPort }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None
{{- end }}