apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: check
  namespace: openshift-gitops
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  description: check Project
  destinations:
    - name: check
      namespace: '*'
      server: 'https://kubernetes.default.svc'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - '*'