kind: Service
apiVersion: v1
metadata:
  name: service
  labels:
    app: app
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  internalTrafficPolicy: Cluster
  selector:
    app: app
status:
  loadBalancer: {}
